# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Site settings
baseurl: "/""
title: "Omar Gloistein Div III"
description: "My Division III portfolio"
permalink: pretty
timezone: America/New_York

collections:
 posts:
   title: Posts # Needed for Siteleaf
   output: true
   description: "My thoughts and ideas"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Blog
  url: /
- title: Categories
  url: /categories/
- title: About
  url: /about/

# Footer nav
navigation_footer:
- title: Back to top
 url: "#top"
